# -*- ruby -*-

require 'rubygems'
require 'hoe'
require 'rake/extensiontask'

Hoe.spec 'stree' do
  developer('Red Davis', 'reddavis@gmail.com')
  self.extra_dev_deps << ['rake-compiler', '>= 0']
  self.spec_extras = { :extensions => ["ext/stree/extconf.rb"] }
  Rake::ExtensionTask.new('stree', spec) do |ext|
    ext.lib_dir = File.join('lib', 'stree')
  end
  # self.rubyforge_name = 'streex' # if different than 'stree'
end

# vim: syntax=ruby
Rake::Task[:test].prerequisites << :compile